server:
    port: 55555

---
spring:
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/shared
#                    search-locations: file:///${user.home}/tmp/spring-cloud-config-server

---
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/risbarov/spring-cloud-config-repository
