server:
    port: 55555

spring:
    application:
        name: spring-cloud-config-server
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/shared
#                    search-locations: file:///${user.home}/tmp/spring-cloud-config-server
    profiles:
        active: native
